<?php
$script='pbbs.php';
$passlog='./lib/passwd.php';
$tmplog='./log/tmp.log';
$countlog='./log/count.log';
$upimgdir='./up/';
$upimgdir_http='';
$imgdir='./img/';
$cookie_hozon='365';
$dbfile='./lib/db_sqlite.php';
$dbfieldsfile='./lib/db_fields.php';
$commonpl='./lib/conf_common.php';
$dbdir='./log/db/';
$kijidb='./log/db/kiji.db';
$maxsize='1000000';
$cookie_name='pbbs';
$skin='skin.html';
$avoid=array('<meta','<form','<embed','script','<style','<!--','<link','<input','<object','frame');
$UPOK=array(
'jpg'=>'1',
'gif'=>'1',
'png'=>'1',
);

?>
