<?php
$max='0';
$pagemax='10';
$titlealt='無題';
$inlink='0';
$w_max='200';
$adicon='0';
$adpass='';
$adicons=array();
$asciideny='0';
$httpdeny='0';
$httpdenynum='1';
$worddeny='0';
$kinsiword=array();
$hostdeny='0';
$kinsihost=array();
$mail='0';
$sendmail='/usr/sbin/sendmail';
$mailto='xxx@xxx.xxx';
$max='0';
$kijinum='';
$colors=array('#000000','#993300','#006666','#3366CC','#CC3300','#996600');
$icons=array('sakana.gif','kani.gif','umigame.gif','kurage.gif','iruka.gif','hitode.gif','tako.gif','harisenbon.gif','kumanomi.gif','kujira.gif');
$icon_names=array('さかな','かに','うみがめ','くらげ','いるか','ひとで','たこ','はりせんぼん','くまのみ','くじら');
?>